version: '3.8'

services:
  echo:
    build: ./
    command: ./echo
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: "root"
      DB_USER: "admin"
      DB_DB: "postgres"
      DB_HOST: "5435"
    depends_on:
      - db
      - redis

  db:
    restart: always
    container_name: db
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres

  redis:
    restart: always
    container_name: redisdb
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=some-redis
      - REIDS_PORT=6379
    image: redis:latest
